# Generated by Django 5.2.18 on 2026-10-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("design", models.JSONField(default=dict, verbose_name="diseño")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "plantilla de diseño",
                "verbose_name_plural": "plantillas de diseño",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "carpeta",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="código corto"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "url",
                    models.URLField(max_length=2000, verbose_name="URL de destino"),
                ),
                (
                    "design",
                    models.JSONField(blank=True, default=dict, verbose_name="diseño"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="archivado"),
                ),
                (
                    "scans",
                    models.PositiveIntegerField(default=0, verbose_name="escaneos"),
                ),
                (
                    "last_scan_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último escaneo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qrs",
                        to="qrcodes.folder",
                        verbose_name="carpeta",
                    ),
                ),
            ],
            options={
                "verbose_name": "código QR",
                "verbose_name_plural": "códigos QR",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("device", models.CharField(max_length=20)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "qr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("qr", "day", "device"), name="uniq_scan_stat"
                    )
                ],
            },
        ),
    ]
