# Generated by Django 5.2.4 on 2026-10-07 23:57

import django.db.models.deletion
import qrcodes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('file', models.FileField(upload_to=qrcodes.models.ficha_upload_to, verbose_name='archivo PDF')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nombre original')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='tamaño (bytes)')),
                ('placements', models.JSONField(blank=True, default=list, verbose_name='QR posicionados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='qrcodes.folder', verbose_name='carpeta')),
            ],
            options={
                'verbose_name': 'ficha PDF',
                'verbose_name_plural': 'fichas PDF',
                'ordering': ['-updated_at'],
            },
        ),
    ]
